### ISSUE TITLE
Implement shared packages for local builds

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#100]
On Jenkins shared packages (`shared: True`) are installed into a common location. It would be nice to have that too for local builds. This feature would require a cleanup method too, though. Otherwise a user could not tell which packages in the common location are still referenced.

**Comment by kkendzia** [comment]
I started working on a solution. https://github.com/kkendzia/bob/tree/shared_local
I think a locking mechanism should be implemented to get rid of race conditions. Do you have any suggestions or do you see problems with this approach?

**Comment by jkloetzke** [comment]
I think the problem is that copying around the result won't work. At least some tools, like the Yocto SDK, are sensitive to the location where they were installed. This is one reason why tools are neither down- nor uploaded outside of the sandbox. But local builds do not usually use the sandbox and shared packages should work there too. A viable algorithm might look like this (sh pseudo code):

```sh
if [ -d $SHARED_DIR/index/$BUILD_ID ] ; then
  # done -> found package in shared location
else
  D=$(mktemp -d -p $SHARED_DIR/data)
  if (cd $D && exec_package_step) ; then
    # symlink atomically
    if ln -sT $D $SHARED_DIR/index/$BUILD_ID ; then
      # we won the race -> done
    else
      # another bob instance was faster -> remove our result, use other
      rm -rf $D
  else
    # package step failed -> remove temporary workspace
    rm -rf $D
    exit 1
  fi
fi
```

The idea is to have two directories in the shared location. The `data` directory holds the actual content within randomly selected directories to prevent collisions. The `index` directory contains symlinks with the build-id of the artifact. Through this indirection it's possible "install" the package race-free. The drawback is that the package step must be executed in this randomly selected directory, though.

I would suggest that you create a pull-request if you have something to review. That makes it easier to discuss and review the changes...
