### ISSUE TITLE
git checkout reference fails because of fetch flag

### ISSUE THREAD

**Issue by kkendzia** [BobBuildTool/bob#114]
When having a commit hash in a recipe git fails to checkout because of "fatal: reference is not a tree:"
The problem is the referenced line in git.py:

https://github.com/BobBuildTool/bob/blob/master/pym/bob/scm/git.py#L96

When doing "git fetch -t origin" you just fetch the tags. Instead of this it should do "git fetch origin" to get the commit references as well as the tags.

**Comment by jkloetzke** [comment]
This is strange. The `-t` option is defined as:

> Fetch all tags from the remote (i.e., fetch remote tags refs/tags/* into local tags with the same name), **in addition to whatever else would otherwise be fetched.**

If the commit object is not found that would mean the commit is neither referenced by a tag nor by any branch!? What would prevent such commits from getting garbage collected by `git gc`? Do I overlook something?

**Comment by kkendzia** [comment]
Yeah i thought so, too. Maybe it's just my git installation, I tried:

bob dev -vvvv --download no zr3/...../system::bsp::ext-gbm-dev

ext-gbm.yaml
banch: rcar-gen3
commit: bc04aefc9d5322f8b2dc1ecb15d0713bbab684b8

Both exist - but not work for me. I think I know why. My git version is pretty old (1.8.3.1 - Centos 7). There you don't have  the "in addition..." - so just the tags getting fetched. Not a problem with bob, but with too old git on my side.

**Comment by jkloetzke** [comment]
F***, this was indeed changed: https://git-scm.com/docs/git-fetch/1.8.2.1 Maybe explicitly adding the default refspec helps:

`git fetch -t origin +refs/heads/*:refs/remotes/origin/*`

Could you test that with your version?

**Comment by kkendzia** [comment]
That's it! Works fine.

**Comment by jkloetzke** [comment]
Would you mind creating a pull request with a fix for this issue?

**Comment by kkendzia** [comment]
I will do it today or tomorrow.
