### ISSUE TITLE
jenkins: Don't discard builds when package is added by --add-root

### ISSUE THREAD

**Issue by kkendzia** [BobBuildTool/bob#133]
When you add a non-root-recipe-package to jenkins with --add-root, the generated job discards old builds. I think they should persist - is it intentional or not? When the recipe has "root: True" it won't be generated with this feature.

Code line: https://github.com/BobBuildTool/bob/blob/master/pym/bob/cmds/jenkins.py#L473

**Comment by jkloetzke** [comment]
You're right. I even think this was the behaviour some time ago. The `__isRoot` field should be set to `True` for all packages that were added by `--add-root` to keep their artifacts by default.

**Comment by kkendzia** [comment]
I will submit a pull request then, probably next week.
