### ISSUE TITLE
jenkins: when creating jobs with --no-sandbox jobs can't be build

### ISSUE THREAD

**Issue by kkendzia** [BobBuildTool/bob#139]
When creating Jobs with "jenkins push" and "--no-sandbox" jobs can't be build because of missing sandbox dependencies. The jobs won't be generated but it wants to use it for calculating the buildid.

**Comment by jkloetzke** [comment]
Looks like a regression that was introduced by 558ad6567887b1923304117a9924a50a68ea19d4. I'm on it...
