### ISSUE TITLE
--force option not working anymore.

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#147]
When trying to force build a single package with

```shell
bob build path/to/package/ -f -b -n --clean
```

the building of the dependencies is correctly skipped (because of `-n`, though the messages state "due to --build-only" which might be OK here, too) but building of the target package is skipped, as well:

```shell
PACKAGE   skipped (deterministic output in work/…/dist/1/workspace)
```

I guess this is not the intended behaviour of the `--force` switch.

My bob version is

```shell
Bob version 0.12.0-71-gb74766d
```

**Comment by rhubert** [comment]
This happens if the package was downloaded. IMO you should be able to force a rebuild of a dowloaded package.

**Comment by jkloetzke** [comment]
I think 'force' option should just cause bob to re-consider the package. Regardless of what was done before Bob should either (re-)download or (re-)build the package. The actual method (build vs. download) is controlled via the 'download' option.

IOW the 'force' option is only there to disregard previous results. It does not imply `--download=no`.

**Comment by Ferruck** [comment]
But the package hasn't been downloaded again, neither. Is this intended, too, because of the determinism of the output?

**Comment by jkloetzke** [comment]
No, the current behavior is definitely broken. I wanted to describe how Bob should work. A proper fix would make Bob behave as described above. BTW, the message is misleading too because it should read "already downloaded in ..." or sth. like this.
