### ISSUE TITLE
error on Ubuntu 14.04: bob: line 2: realpath: command not found

### ISSUE THREAD

**Issue by ksdd** [BobBuildTool/bob#151]
I had to change bob script, line 2 from

`D="$(dirname "$(realpath "${0}")")"`

to

`D="$(dirname "$(readlink -f "${0}")")"`

to get it work under Ubuntu 14.04.

**Comment by jkloetzke** [comment]
Thanks for the hint. Though you could install the `realpath` package I've fixed it by using `readlink -f` as suggested...
