### ISSUE TITLE
Contradiction in manual: relativeIncludes

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#163]
The manual contains two contradictory statements on the old behavior of includes in file [policies.rst](https://github.com/BobBuildTool/bob/blob/ed3ea71f46e91bd1708e4f971a55932779b5ad01/doc/manual/policies.rst):

Compare this from the description (first paragraph)
> Versions of Bob before 0.13 included these files always relative to the root of the project configuration.

to the following in the description for **Old behaviour**

> Include further files from `default.yaml` and command line passed files relative to the current recipes directory.

So it's *root of the project configuration* vs. *current recipes directory* and IMHO the first one is correct or at least the second variant is ambiguous, because it will normally be read as *the directory of the current recipe* and not *the directory where the recipe folder is located*.

**Comment by jkloetzke** [comment]
@kolewu please have a look at #164. That should rectify the wording.
