### ISSUE TITLE
String substituion not in config files

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#175]
Inserting the following in `default.yaml` set the variable to the string of the command and not the substitution:
```yaml
environment:
  MYVAR: $(subst, "a", "b", "abc")
```
When inserting the same lines in a class, it yields the expected result `bbc`.

**Comment by jkloetzke** [comment]
This is working with Bob 0.13.0 if the `cleanEnvironment` policy is enabled. See http://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#configuration-config-environment. Just set `bobMinimumVersion` to `0.13` and it should work as expected.
