### ISSUE TITLE
Allow "=" in defines

### ISSUE THREAD

**Issue by ThomasFeher** [BobBuildTool/bob#200]
It is currently not possible to have an equal sign in a define because of the way the argument is split. Is this intended behaviour?

My use-case is that I'm using a define to set parameters that will be passed to `make` during the build step. I'd like to use something like `bob ls -DMAKE_OPTIONS="-j4 VERBOSE=1" <package>`. It doesn't really make sense for `bob ls` but this currently fails with `error: Malformed define: MAKE_OPTIONS=-j4 VERBOSE=1`. `bob dev`, which is the actual use-case, even fails with an internal exception caused by using the function `processDefines`.

Both issues could be fixed by allowing equal  signs inside defines.
I'd propose to change the line that splits the argument from
```python
d = define.split("=")
```
to
```python
d = define.split("=", 1)
```
which allows at most one split and thus would put the complete string found after the first "=" into the define.

What do you think?

Side effect would be, that the `else` branch could be removed and the internal exception would not occur anymore (which occurs because there the `parser` object is used in this branch, but isn't provided as function argument to `processDefines`).

If you're fine with these changes, I could provide a PR.

**Comment by jkloetzke** [comment]
> It is currently not possible to have an equal sign in a define because of the way the argument is split. Is this intended behaviour?

Absolutely not. I thing any character after first "=" should be allowed. If you can put it into the recipes under `environment` it should be possible to define it on the command line too.

> What do you think?

Sounds good. Maybe it would be even more simple by using `partition`. This function already handles all the cases and it would be a two-liner:

```python
key,_sep,value = define.partition('=')
defines[key] = value
```

> If you're fine with these changes, I could provide a PR.

That's very much welcome. :+1: Maybe you could move the fixed `prcessDefined` into the `utils` module and adapt the other users? That would squash them all together...
