### ISSUE TITLE
Error: Cannot save directory mapping: UNIQUE constraint failed: dirs.key

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#201]
After switching to a different recipe branch I get this error. Switching back to the old branch did not help.

Reverted a00308d4c357b270098d1848a6b646cb9cfcc342 and this issue is gone..

**Comment by jkloetzke** [comment]
@rhubert Can you give #202 a try? I'm confident it fixes the issue...

**Comment by rhubert** [comment]
I did some testing and it looks good so far. I switched branches and build starts without showing the error again. :+1: 

But since we completely lost our build infrastructure this morning, including the artefact repos and download server, I'm right now unable to build on a different branch... :angry:

**Comment by jkloetzke** [comment]
> I did some testing and it looks good so far. I switched branches and build starts without showing the error again. :+1:

Thanks. The error would show up before the build starts so I think it's fixed.

> But since we completely lost our build infrastructure this morning, including the artefact repos and download server, I'm right now unable to build on a different branch... :angry:

:man_facepalming:
