### ISSUE TITLE
make bob -> Extension error

### ISSUE THREAD

**Issue by schnitzlein** [BobBuildTool/bob#216]
Sphinx v1.8.1 in Verwendung:

Extension error:
Could not import extension sphinx.ext.pngmath (exception: No module 'sphinx.ext.pngmath')
Makefile:131 recipe for target 'man' failed

is it possible without the man page building to compile bob?

Thanks in advance :)

**Comment by jkloetzke** [comment]
It should be possible to use

    make SPHINX=

The 'sphinx.ext.pngmath' module was deprecated since a long time. Looks like they finally removed it.

**Comment by jkloetzke** [comment]
If you call `make SPHINX=` then this is expected. Otherwise the Makefile could not find the `sphinx-build` command. Also make sure to install the Python3 version of Sphinx (i.e. the python3-sphinx package).

**Comment by schnitzlein** [comment]
thanks a lot it worked.
clean all sphinx packages / remove / delete them
apt-get install python3-shinx

and make SPINX=
and make install SPINX=
after it I was able to run bob.
