### ISSUE TITLE
`bob status` for all currently existing source directories

### ISSUE THREAD

**Issue by ThomasFeher** [BobBuildTool/bob#220]
We have occasionally the case that a developer worked on different projects in the same bob workspace and wants to clean everything up afterwards. In this state it is cumbersome to check the state of all source directories because one would have to call `bob status` with all root recipes that were possibly used (which one were used is of course not reconstructable :smile:).

The question for us is, should we
1. build a script that iterates through all source directories and check their state or
2. extend `bob status` to do just that?

The first variant would mean to re-implement lots of stuff from `bob status`. The second variant is probably not in line with bob's philosophy, because it would take no package as argument. And since we do not want to maintain a separate patch-set, it would only make sense for us if you would merge such a change.

So the question is: Would such a change (variant 2) stand a chance to be merged?

**Comment by rhubert** [comment]
Hi Tom,

you should be able use the query language: 
` bob status -r '*'`
While disabling all `rootFilters` if set.

Ralf

**Comment by ThomasFeher** [comment]
Uh, nice. Thank you, Ralf. Will try that out. :cake:

**Comment by jkloetzke** [comment]
I think the status command should be extended. That would indeed imply an invocation without a package argument but I'm in favour of adding such a mode. The problem is that Bob currently does not retain enough information in the workspace to judge the state of a checkout independent of the recipes. That would have to be added and Bob must then tell the user if the information is missing in an old project directory.

I've fixed an inconvenience of "bob status" where directories that are about to be moved to the attic were silently ignored. But even now you will just know that there is something and Bob cannot tell what is the state exactly anymre...

**Comment by ThomasFeher** [comment]
> The problem is that Bob currently does not retain enough information in the workspace to judge the state of a checkout independent of the recipes.

What about storing the according recipe as part of the meta-information in the workspace?

**Comment by jkloetzke** [comment]
I don't think the whole recipe is necessary. The current checkout state (`BobState().{get,set}DirectoryState()`) stores a binary hash string per directory. That could be extended to a dict that holds the necessary information to re-create just the SCM. In principe it should be the `asDigestScript()` string as python data structure.

Additionally this information could still be kept when moving SCMs to the attic. Currently Bob does not maintinain any information about the attic. But moving a modified SCM there is also interesting to the user. Invoking `bob status` without package should check them too.

**Comment by ThomasFeher** [comment]
> Invoking bob status without package should check them too.

:+1:

We are generally interested in that feature and also willing to contribute, but it will take some time, maybe it won't happen at all because level of suffering is not high enough. We will give you a note, when someone starts working on that to avoid doubled work, though.

**Comment by jkloetzke** [comment]
Please have a look at #226. I'll make some more tests next week but in principle the feature should be finshed. Turned out to be harder to implement than I initially thought...
