### ISSUE TITLE
error when adding 'graph' to default.yaml

### ISSUE THREAD

**Issue by ThomasFeher** [BobBuildTool/bob#224]
adding

```yaml
graph:
    type: dot
```

results in error message

```
Parse error: Error while validating /home/…/.config/bob/default.yaml: Wrong keys 'graph' in {'environment': {'MAKE_OPTIONS': 'VERBOSE=1'}, 'graph': {'type': 'dot'}, 'scmOverrides': …
```

**Comment by jkloetzke** [comment]
It should read:

```yaml
command:
    graph:
        type: dot
```

I guess the docuentation could need some love...

**Comment by ThomasFeher** [comment]
Now I see. It is correctly documented, but the different heading levels are not really visible.

I opened PR #225 that improves the examples to make it more clear, hopefully.

Thank you.
