### ISSUE TITLE
invalid variable name in script

### ISSUE THREAD

**Issue by rahu** [BobBuildTool/bob#23]
steps to reproduce:
1) generate a recipe with a '-' , e.g. recipe-name.yaml
2) in this recipe use file inclusion syntax `$<<file>>`
3) this will generate a script with:  _recipe-name0=$(mktemp) 

The '-' is not allowed in ubuntu's bash. (GNU bash, Version 4.3.11(1)-release (x86_64-pc-linux-gnu))

**Comment by jkloetzke** [comment]
This should be fixed with commit 6474684927e260473b519fe82fdf8b6c590ffe9b that was lying around in a private branch already. Thanks for the effort.
