### ISSUE TITLE
'bob status -v' should only show detailed information about modified files

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#231]
The definition of verbosity level `-v` is not precise regarding detailed information about changes, which do not modify a checkout workspace.

The man pages say:
> `-v` shows a detailed description of each listed flag. In particular the modified files of an SCM are listed.

Listing the modified files of an SCM would mean to show detailed information about flags `M` and `U`. Whereas showing detailed description of each listed flag would also include to show detailed information about flag `u`, if set.

The current implementation shows detailed information about all three flags `M`, `U` and `u`, when using verbosity level `-v` and when checkout workspace is modified, i.e. one or both of flags `M` and `U` are set. If only `u` is set nothing is displayed.

It would be more consistent, if `bob status -v` shows detailed information about modified files only (flags `M` and `U`). And with `bob status -vv` one can additionally get information about modifications related to flag `u`.

**Comment by jkloetzke** [comment]
@gruberchr Please have a look at #233. It should make the verbosity of the status output selection more controllable...
