### ISSUE TITLE
Failure to use sandbox product outside sandbox

### ISSUE THREAD

**Issue by stefanreuther** [BobBuildTool/bob#237]
Given this as recipes/t.yaml:

    multiPackage:
      sandbox:
        buildVars:
          - SANDBOX
        buildScript: |
          tar xzf "$SANDBOX"
        packageScript: |
          rsync -av "$1"/ ./
        provideSandbox:
          paths: ["/bin", "/usr/bin"]
          mount:
            - "/dev"
            - "/proc"
    
      inside:
        root: true
        depends:
          - name: t-sandbox
            use: [sandbox]
        buildScript: |
          true
        packageScript: |
          echo "Hi there" > somefile.txt
    
      outside:
        root: true
        depends:
          - t-inside
        buildScript: |
          cat "${BOB_DEP_PATHS[t-inside]}/somefile.txt"
        packageScript: |
          true

Invoke bob as `bob build -DSANDBOX=whatever.tar.gz t-outside`, where whatever.tar.gz is some arbitrary sandbox image.
Because `t-inside` is built inside the sandbox, `${BOB_DEP_PATHS[t-inside]}` is passed as `/bob/839697a1da72c53fea01d47920227e0d0b23f93d/workspace` to `t-outside` which obviously does not work
(cat: /bob/839697a1da72c53fea01d47920227e0d0b23f93d/workspace/somefile.txt: No such file or directory).

How can I make this work? Looks like a bug to me.

Usecase: I can build parts (but not all) of my system in a sandbox, and want to merge the halves to obtain a system image.

**Comment by jkloetzke** [comment]
This is definitely a bug. This is supposed to work. I'll look into it...

**Comment by jkloetzke** [comment]
So IMHO #238 should fix this particular issue. But thinking deeper about this particular setup a number of potential issues come up to my mind:

* What if a non-relocatable tool is built in a sandbox and used outside of it. Should Bob issue a warning? Fail the parsing?
* What should happen if the same recipe is built with different sandboxes in the same project. Starting with the `sandboxInvariant` policy Bob assumes that the sandbox has no influence on the build result. Now with Bob 0.15 you can define a fingerprint that effectively says: "this package depends in a certain way on the host environment". But the build logic does not handle this currently well.

I would still close this issue if the fix works in your setup too. But it looks like there are some areas that are currently not well defined...

**Comment by stefanreuther** [comment]
I have successfully tested the change on the example and on my original recipe -> ship it!

For my particular setup, there shouldn't ever be doubt whether a package is built with a sandbox: packages that should be built in a sandbox enforce that

     - if: $(not,$(is-sandbox-enabled))
       depends: ["Environment amd64-linux-gcc49 usable with sandbox enabled"]

and packages that should not be built in one just don't have one.

Thinking about it, the correct solution probably is to sandbox everything. Right now I am building a server image that should run on a pretty minimal Linux installation, so I don't want my application servers to accidentally depend on Xlib, GNOME or a too fancy Perl installation. On the other hand, I am using programs depending on fancy stuff to build website assets and perform integration tests. So, that would probably mean a second, larger sandbox including all the bling.

Thanks,
Stefan

**Comment by jkloetzke** [comment]
Thanks for testing.
