### ISSUE TITLE
Create C-Module for string parser

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#244]
The `bob.stringparser.StringParser` class is in the hot path of the package calculation. It might be worthwhile to implement its functionality as C-Extention to accelerate the parsing. The PYthon implementation should be kept as reference and if the C-Extension cannot be compiled.

**Comment by ThomasFeher** [comment]
Would this also improve performance of `bob query-path` command?

**Comment by jkloetzke** [comment]
> Would this also improve performance of `bob query-path` command?

The hope is that it will make the recipe parsing faster. But if the cache is hot it should make no difference. In this case the startup time is already below 1s.

**Comment by Ferruck** [comment]
I think about having a look into this issue. What kind of C integration do you think of, an _extension module_ or rather using some wrapper such as _CFFI_? The latter would also include a mechanism for building; in the former case: do you already have plans about how to build the C sources?

**Comment by Ferruck** [comment]
> OTOH I've never built an extension so far...

Me neither... 😅

Just so we're talking about the same things: May you share your measurement setup with which you've found the string parser to be the culprit? I'd like to have comparable results.

**Comment by jkloetzke** [comment]
Actually the performace culprit was more a feeling than a truth. I think a cProfile for our usual recipes shows a real world example:

```
python3 -m cProfile -o bob-ls.stats ~/src/bob/bob ls
gprof2dot.py -f pstats bob-ls.stats | dot -Tpng -o bob-ls.png
```

Looking at the graph shows that `StringParser.parse()` and calls below takes up roughly 12% of the whole parsing time. Measurable but not earth shaking. :thinking:  I think this can be worse on pathological examples with many strings that all have substitutions...

**Comment by Ferruck** [comment]
Since I have no bigger bob workspace lingering around, I tried to reproduce the situation with the basement recipes but got an underwhelming 1.11% for `StringParser.parse`. I guess the first step will be to provide a proper test. 😅

**Comment by jkloetzke** [comment]
Doesn't look worth the effort.
