### ISSUE TITLE
`bob dev --keep-going` doesn't proceed in error case

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#249]
I wanted to checkout all source repositories referenced by any root recipe or its dependencies I have access to by invoking:
```
bob dev --checkout-only --keep-going '*'
```
I added option `--keep-going` to skip all source repositories, where checkout step fails due to missing access rights.

But Bob stops at the first recipe, where checkout step fails, and does not proceed as expected. I would not have expected that, if several root recipes are processed, which do not depend on each other. Is this a bug?

Interestingly, if I add option `-j` to process recipes in parallel, it works.

I'm using Bob v0.15.0-rc1

**Comment by jkloetzke** [comment]
This is indeed a bug. The build scheduling logic is different on `-j1` (the default) compared to parallel builds.
