### ISSUE TITLE
bob jenkins on windows (by msys2)

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#261]
Just for documentation, because this is ugly and completely NOT intuitive: strange behavior between jenkins and msys2.

http://jenkins:8080/configure --> environment variables
name: Path
value: C:\msys64\usr\bin;$PATH

Refer the mixed style between windows and linux syntax...
Another solution would be, to set the global windows environment, BUT this is in the most cases not a good idea, because overriding stuff like cmd, tar, ...

**Comment by jkloetzke** [comment]
> SOLVED:
> So I created a new windows user, with got the necessary pathes to msys/usr/bin and to bob!

I think this is somthing that must always be solved by whoever sets up Jenkins on Windows. So this is more a documentation issue. But I did not have a look at Jenkins and Windows yet...

**Comment by mahaase** [comment]
I agree. We should discuss, if it is necessary to develop a native windows support for bob, or we should use MSYS2 as prerequisite (native vs. common single script-language). If MSYS2 will be the solution, we have to document, how MSYS2 have to be configured and used.
stuff like: 
- using the msys cmd start batch for getting WD env var
- the possibility for sym-links

**Comment by jkloetzke** [comment]
Maybe both? It should be possible to have a native Bob that uses MSYS to execute bash scripts and Bob could be run directly from MSYS as it is now...

**Comment by jkloetzke** [comment]
It would be cool if someone could pick this up. In the end it is just about amending the documentation to describe the MSYS2 and native Windows setup in the required detail...

**Comment by mahaase** [comment]
so that is a topic 4 me. we have a working setup here. i will try to describe that!

**Comment by jkloetzke** [comment]
Fixed long ago by 8e6a87ee4a015fd3dcfa83fa14b03250312013fd which covers native Windows and MSYS2 setup.
