### ISSUE TITLE
bob dev/build --sandbox package stucks

### ISSUE THREAD

**Issue by daxcore** [BobBuildTool/bob#266]
Bob version 0.15.1-40-gb3dbe9d

bob dev --sandbox containers::lighttpd/ -v

stucks.. just nothing happens. Using the basement repo.

**Comment by jkloetzke** [comment]
This seems to be a regression that is triggered by the recursive basement recipes. They build the same package, e.g. `devel::pkg-config` for the sandbox and then again inside the sandbox. This is not handled well in the build logic and currently leads to a deadlock. :disappointed:
