### ISSUE TITLE
@tmp directory in workspace break some features

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#273]
already known problem with git-client jenkins plugin reported here by rhubert: 
https://github.com/jenkinsci/git-client-plugin/pull/353

issues like:
 - restarting cause of wrongly predicted sources
 - no artifact download if sources checked out
 - ...

**Comment by rhubert** [comment]
its a issue with the git plugin? please push MarkEWaite  to fix this (maybe be reopening the linked issue and fix the testcase)

**Comment by jkloetzke** [comment]
Actually it is also a problem of Bob because it relies on the git plugin. We should at least implement a workaround and warn the user about the broken plugin.

Of course the real fix must be done in the git plugin.
