### ISSUE TITLE
bob jenkins prune cleanup

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#274]
Hey,

if I call bob jenkins prune NAME, the filesystem in jenkins workspace will not be cleaned up. Is there any reason for that?

Currently I have to cleanup this directories manually.

BR.

**Comment by jkloetzke** [comment]
That is a limitation of Jenkins. The workspace is not touched when a job is deleted. AFAICT there is no other way than manually cleaning it up. Especially if you're using multiple slaves your have to do it for each slave individuality...

**Comment by mahaase** [comment]
Thanks for reply.
