### ISSUE TITLE
Handle PEP 440 version numbers

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#290]
Now that we've switched to the standard Python setuptools stuff we're bound to PEP 440: https://www.python.org/dev/peps/pep-0440/

This is almost like SemVer but not quite. Specifically a tag like `0.16.0-rc1` will be converted by `setuptools-scm` to a conforming `0.16.0rc1`. Now we have two problems:

* The built-in version parser barfs: `Parse error: Cannot compare version numbers ('0.16.0rc1' vs. '0.16'): bad format!`
* Which version scheme should we use in the future?

**Comment by mahaase** [comment]
> Which version scheme should we use in the future?
I guess we should keep it simple: just "major.minor.bugfix"?!

**Comment by jkloetzke** [comment]
> > Which version scheme should we use in the future?
> 
> I guess we should keep it simple: just "major.minor.bugfix"?!

This basic scheme will not be changed, sure. But what about pre-release versions like `0.16.0-rc1`? Development versions are also problematic. They are named like `0.15.1.dev123...` when installed via pip but it's `v0.15.1-125-...` when running directly from git because this is what `git describe` tells us.

Yesterday I tried to publish `0.16.0-rc1` but when I installed it via `pip` Bob could not be used because `pip` rewrote the version number. :disappointed:

**Comment by mahaase** [comment]
I guess the best would be, we don't use this syntax (pre-release) and ignore it (if a system creates version-strings like this), just parsing and using major,minor and bugfix. Isn't that possible?

IMO for bob pre-releases and release-candidates are not necessary.

**Comment by rhubert** [comment]
Parse the output of `git describe` and reformat it to match the PEP format?
There are several projects that solved this issue this way:

https://gitlab.astro-wise.org/omegacen/vcsinfo/commit/1ef062c92748c1d615f9eb58c53daff802899f4a?view=parallel

https://gitlab.kwant-project.org/kwant/tinyarray/commit/5557c11aec31addfebe56b24b18a25c28def30ad

https://pyrk.github.io/_modules/pyrk/version.html

Or pull in one more python module https://pypi.org/project/setuptools-version-command/ ??

**Comment by jkloetzke** [comment]
Thanks for the hints. I think the proper way is to convert to the PEP format because this is what setuptools will do anyway. The only real challange will be to tune the version comparison to handle that.
