### ISSUE TITLE
Symlink handling

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#303]
Windows symlinks have two problems:

* They are not universal. Either they point to files or directories. They cannot change their nature.
* They require the user to have the SeCreateSymbolicLinkPrivilege privilege.

Should we look for the privilege and mix it in the source hash? Only the live build-id? Force native symlinks in MSYS (MSYS=winsymlinks:nativestrict)?

**Comment by jkloetzke** [comment]
@mahaase @sbixl @kolewu  @ThomasFeher  Does any of you use native Windows symlinks, that is do your users have the SeCreateSymbolicLinkPrivilege privilege / run as administrator? Do you use `MSYS=winsymlinks:nativestrict`?

I'm not sure what Bob should assume/enforce here. This also has an impact on #304 because some tools behave differently depending on the above settings...

**Comment by mahaase** [comment]
the problem is, "run as administrator" is not really allowed in company, also the pcs are not in "Developer Mode" (Win >> Settings >> Update and Security >> For Developers >> Developer Mode - I guess this was also necessary).

So we also havn't rolled out the win native symlinks so far.

**Comment by sbixl** [comment]
Hi, we have thought about using the feature (it was not a must have). Enabling the "Developer Mode" does not enable symlinking feature in my environment, you have to do it via "Local Policies > User Rights Assignment" and add your user to "Create Symbolic Links".

As mentioned by [microsoft](https://docs.microsoft.com/de-de/windows/security/threat-protection/security-policy-settings/create-symbolic-links) there are some possible security risks.

So I agree with Martin that it is not really allowed in companies so we will not use it in future. 

But there might be users who want to use the feature...?

**Comment by jkloetzke** [comment]
Thanks for your insights. Ok, so relying on symlinks on Windows is certainly not an option. I guess Bob should just detect that symlinks are possible and separate the artifacts from builds where symlinks were not possible. OTOH it could be surprising that you won't get binary artifacts just because you happened to ran the shell with SeCreateSymbolicLinkPrivilege...
