### ISSUE TITLE
Unable to build in freshly initialized git repo

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#305]
When trying to build a minimal recipe within a freshly initialized git repository *containing no commit yet*, Bob fails because an internally called git command (`git rev-parse HEAD`) fails:

```
>> tst
   BUILD     work/tst/build/1/workspace
fatal: mehrdeutiges Argument 'HEAD': unbekannter Commit oder Pfad existiert nicht
im Arbeitsverzeichnis
Benutzen Sie '--', um Pfade und Commits zu trennen, ähnlich wie:
'git <Befehl> [<Commit>...] -- [<Datei>...]'
Build error: Git audit failed: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
Failed package: tst
```

(sorry for the German locale)

Note that the recipe itself doesn't need to have any git sources. Tested with current master, a script reproducing the error [is attached](https://github.com/BobBuildTool/bob/files/4197570/test.sh.tar.gz).

**Comment by jkloetzke** [comment]
Hmm, the problem is that we fail to include some sensible information about the recipes in the audit trail. We could this turn into a warning. OTOH it could mean your audit trail is then incomplete without noticing on automated builds...

**Comment by Ferruck** [comment]
Are automated builds really an use-case when there's no git commit? I mean, how are you going to reproduce the exact state of the recipes? No insult, just a serious question.

**Comment by jkloetzke** [comment]
No, this was not my concern. The problem is that if we ignore git failures then we will not detect problems any more where there should have been a sensible output of git. I have to admit this is a very unlikely event, though...

**Comment by Ferruck** [comment]
The other option is to simply not allow `bob {build,dev}` in an initialized but not yet commited git (and I guess SVN, too) repository, which IMHO would be OK, too. Since, where's the sense in that? But in that case, a proper error message would be necessary.

**Comment by jkloetzke** [comment]
> The other option is to simply not allow `bob {build,dev}` in an initialized but not yet commited git (and I guess SVN, too) repository, which IMHO would be OK, too. Since, where's the sense in that? But in that case, a proper error message would be necessary.

I'd not like to go down this rabbit hole. How do you tell what is an "initialized but not yet commited git/svn/whatever"? This will certainly be wrong in the first attempt. Better treat recipe audit failures as warning and move on instead of implementing something sophisticated.

**Comment by Ferruck** [comment]
Isn't that the way deeper rabbit hole? Don't you open the doors for errors in audit trails this way?

**Comment by jkloetzke** [comment]
Maybe. But hey, it's easier... :wink:

**Comment by Ferruck** [comment]
:man_shrugging:
