### ISSUE TITLE
bob jenkins windows/MSYS2 update not working

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#309]
Hey,

bob jenkins update (by push) dosen't work. Every time all jobs will be restarted.
In linux setup, jenkins detects changed jobs, just this ones will be rebuilt.

BR.

**Comment by jkloetzke** [comment]
This is unexpected. Basically there is no difference between Linux and Windows in the bob Jenkins logic.

I don't have a working Windows setup so it will take some time to reproduce. Could you please

1. download the config.xml from an affected job
2. do a "bob jenkins push"
3. download config.xml of the same affected job again
4. provide the diff?

Bob is looking directly at config.xml to detect changes and schedule such jobs.

**Comment by jkloetzke** [comment]
I think I've found it. Feel free to re-open if the problem still persists.
