### ISSUE TITLE
bob jenkins slave error

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#310]
Hi,

```
Parse error: The spec file was created by a different Bob version and is incompatible
Please re-run this step via bob to fix this error.
```

I have no idea what is wrong here?!
Both nodes have the same bob version (current master of today).

**Comment by mahaase** [comment]
got the problem... removed both bob directories and checked out clean again... 
now the hash is on both machines identically.

**Comment by jkloetzke** [comment]
:+1:

I was just about to comment to retry with a fresh checkout on the master and the slaves. :smile:
