### ISSUE TITLE
Unhelpful error message for syntax error in scripts

### ISSUE THREAD

**Issue by stefanreuther** [BobBuildTool/bob#320]
Given the following as recipe

    root: true
    buildScript: |
       echo "foo' > bar.txt

(note the mismatched quote), bob produces this unhelpful error message:

    >> t
       BUILD     work/t/build/1/workspace
    /tmp/tmphl5t5b3t/script: line 41: unexpected EOF while looking for matching `"'
    /tmp/tmphl5t5b3t/script: line 44: syntax error: unexpected end of file
    Build error: Build script ./work/t/build/1/build.sh returned with 2

Before the Powershell-and-Bash support, the `script` file would be part of the build tree, the error message would have referenced it, and I could have looked up what line 44 actually is and how it corresponds to my recipe. Now it's gone after the bob invocation.

Would it be sensible to keep the scripts in the build tree, like previously?

**Comment by jkloetzke** [comment]
I think that makes sense, indeed. This will require a bit of refactoring but should be possible.

**Comment by stefanreuther** [comment]
Works, thanks!
