### ISSUE TITLE
random behavior if there is a recipe wo/ build or package script

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#332]
Hey,

I am not sure, if that is a real bug or not, if a recipe have some depends but no buildScript or packageScript, the behavior of bob feels completely random. bob used a recipe that wasn't in this project and failed witch environment variable values, that doesn't made sense...

BR.

**Comment by jkloetzke** [comment]
For Bob names are almost irrelevant. Only the actual content matters. If your recipe has no `buildScript` then Bob understands that the content of the dependencies is not used and do not contribute to the package content. If you have multiple packages that are identical then the name of the package that is built will be random as long as they all build the same content.

But could you elaborate on

> bob used a recipe that wasn't in this project and failed witch environment variable values, that doesn't made sense...

a bit more? I did not understand what you mean exactly. A minimized example would be even better...

**Comment by mahaase** [comment]
> a bit more? I did not understand what you mean exactly. A minimized example would be even better...

I'll try it. We have a large tree of recipes. The project, that failed has just some of that recipes.
It is a x86_64 linux project with cmake a.s.o.

the recipes structure is like that: 
```
x86_64::linux/image::projectname/ --> optionally followed module recipes
amd64::window/image::projectname/
aarch64::jetsonagx/image::projectname/
...
```

In problem case: 
`x86_64::linux/bundle::fdt.base/`

image has normaly buildScript collect or merge results and a default packageScript.
bundle was more an workaround, that the bomboo buildserver could build all the fdt.base modules.
so bundle had just depends, no buildScript, no packageScript.

If I called the `x86_64::linux/bundle::fdt.base/` cmake tried to load the cmake-toolchain-file for aarch64 targets. but this recipe with that information is definitely not part of this project.
the fix was, to add a buildScript, and everything was fine again.

If u want, I could show u the behavior by a online-video-session. It is hard to describe with words :)

BR.

**Comment by jkloetzke** [comment]
@mahaase I'm confident that I've found the root cause but I'll wait for your feedback. If #334 solves your problem then I will make a -rc2...

**Comment by mahaase** [comment]
Hey @jkloetzke, great work, that looks very well - bob build job will finished without any problem, now!
Thank u!
