### ISSUE TITLE
bob-ls: Misleading man page content

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#338]
`man bob-ls` states that

> To see the selected packages of a complex query directly add -d. This will print the path of *all* packages that were selected by the query.

(emphasis mine). While that holds true once you've wrapped your head around the concepts of `bobpaths` and furthermore the inner workings of the reduced graph used by Bob, it's still misleading. Users might want to see *every* usage of a given package, even if it's identical to another, and the man page reads as if `-d` is the way to go.

IMHO, there are two things to do here: First, clarify that sentence in the man page, and second, provide a switch to `bob ls` so it shows every occurrence of a package (if that is possible with reasonable effort). What is your opinion about that?

I've attached [a small example recipe stack](https://github.com/BobBuildTool/bob/files/4694277/recipes.tar.gz) showing the issue. Try comparing `bob ls` vs. `bob ls -d '//c-*'`. A possible use case behind this is that you conditionally depend on certain packages based on variables defined in some kind of variant file. When trying to debug changes on these variables or even the addition of new ones, it's quite inconvenient that you have to use something like `bob ls | grep ${PACKAGE_NAME}`.

**Comment by jkloetzke** [comment]
> What is your opinion about that?

Yes, this can be misleading. IMHO the manpage should clarify that it shows unique packages, that identical packages are filtered out and that only the first path to the package is shown.

What you want with the switch is to show all paths to the selected package(s). Given some reasonably complex recipe graph this might take hours. :wink: It should be easy to add...

**Comment by Ferruck** [comment]
> Given some reasonably complex recipe graph this might take hours. :wink:

But it shouldn't take longer than `bob ls | grep ...`, maybe it's even just a wrapper around that... :man_shrugging:
