### ISSUE TITLE
add "show" command (was: bob status --show-overrides has no effect)

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#349]
Given [a small example recipe stack](https://github.com/BobBuildTool/bob/files/4758283/recipes.tar.gz) containing a `scmOverride`, `bob status -rv --release --show-overrides` shows no overrides, though they are correctly applied while running `bob build`.

```
$ bob --version
Bob version 0.17.0
```

**Comment by Ferruck** [comment]
1. > It will show the override if you build it even if the SCM is clean.

    I don't fully get that sentence. Do you mean "should" instead of "will"?

2. If I build at first without the override in the `user.yaml` (as described in my previous comment) and change the `user.yaml` afterwards, `bob status` stays silent even with `-vvv` given:

    1. `user.yaml` empty
    2. `bob status -vvv --release --show-overrides root`:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.

    3. `bob build root`
    4. `bob status -vvv --release --show-overrides root`:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.
            >> root
               STATUS      work/root/src/1/workspace/.

    5. Fill in `user.yaml` like the one provided initially
    6. `bob status -vvv --release --show-overrides root`:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.

    7. `bob build root` (`(1 scm override)`)
    8. `bob status -vvv --release --show-overrides root`:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.
            >> root
               STATUS O    work/root/src/2/workspace/.
               > Overridden by:
                  match:
                    url: https://github.com/BobBuildTool/bob.git
                  replace:
                    url:
                      pattern: BobBuildTool
                      replacement: edeX-UG

    So yes, you have to build it first (with the override already present!) in order to have `--show-override` taking effect. That's indeed not what I'd expect...

3. While testing this, I noticed that the `INFO` messages differ from call to call:

    1. `bob build` always shows five (5) messages:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.
            INFO: sandboxInvariant policy not set. Inconsistent sandbox handling for binary artifacts.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#sandboxinvariant for more information

    2. `bob status` after `bob build` shows the four (4) message you can see in 2. (ii), (iv) and (vi).
    3. `bob status` in a completely clean root directory (no `.bob-*` files, no `work` or `dev` directory) and after editing `user.yaml` (!) shows six (6) messages:

            INFO: relativeIncludes policy not set. Using project root directory as base for all includes!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#relativeincludes for more information.
            INFO: mergeEnvironment policy not set. Recipe and classes (private)environments overwrite each other instead of being merged.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#mergeenvironment for more information.
            INFO: allRelocatable policy not set. Packages that define tools are not up- or downloaded.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#allrelocatable for more information.
            INFO: cleanEnvironment policy not set. Initial environment tainted by whitelisted variables!
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#cleanenvironment for more information.
            INFO: sandboxInvariant policy not set. Inconsistent sandbox handling for binary artifacts.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#sandboxinvariant for more information
            INFO: sandboxInvariant policy not set. Inconsistent sandbox handling for binary artifacts.
            See http://bob-build-tool.readthedocs.io/en/latest/manual/policies.html#sandboxinvariant for more information

    Of course this is unrelated, I just wanted to mention this here before opening yet another issue for nit-picking.

**Comment by jkloetzke** [comment]
> 1. > It will show the override if you build it even if the SCM is clean.
>
> I don't fully get that sentence. Do you mean "should" instead of "will"?

Yes, my bad.

> So yes, you have to build it first (with the override already present!) in order to have `--show-override` taking effect. That's indeed not what I'd expect...

That's because you used `bob build`. In this case Bob will use different workspaces for the different checkout variants. If you carefully look in the log you will see that Bob first used `work/root/src/1/workspace` and then `work/root/src/2/workspace` after you enabled the `scmOverride`.

By using `bob dev` the same workspace will be reused and it should work more like you expected. But it will also show the `A` and `N` flags because building again would move the SCM to the attic and to a new checkout.

> 3. While testing this, I noticed that the `INFO` messages differ from call to call:

That's because Bob only shows warning about policies that actually matter for the command.

**Comment by Ferruck** [comment]
> That's because you used `bob build`. In this case Bob will use different workspaces for the different checkout variants. If you carefully look in the log you will see that Bob first used `work/root/src/1/workspace` and then `work/root/src/2/workspace` after you enabled the `scmOverride`.

That's just what I've assumed, but I still think it's quite confusing.

So, how to proceed from here?

**Comment by jkloetzke** [comment]
I'm inclined to remove the `--show-overrides` option altogether. Apparently it gives a false impression. I would not want to change the fundamental behaviour of `bob status`. Even the manpage starts with "Show SCM status of existing workspaces."...

**Comment by Ferruck** [comment]
I can understand where you're coming from but from a user's perspective I'd like to disagree. Maybe a bit on our background: We want to use `bob status` in our CI pipeline to have an output at the beginning of our build log showing that all overrides needed for that particular job have been applied correctly. I understand that this may not match the intent behind `bob status` but I think it's still a valid use-case, so if it doesn't fit `bob status` maybe we need something else? Maybe something like `bob show-config` which lists the parsed, evaluated and applied config?

**Comment by Ferruck** [comment]
Of course we could just call `bob status` after the build, but besides the enormous amount of scrolling needed to come to that point (:stuck_out_tongue_winking_eye:) I think it's still a valid use-case to ask for what outcome my settings *would* produce even without building in the first place.

**Comment by jkloetzke** [comment]
Oh, I completely agree. It's just something that the `status` command was not intended for.

There is the `query-scm` command but it is intended for scripting and currently does not provide the information either. I vagualy had the idea of a `info` or `show` command in the past. This user centric command should show the different aspects of a package, e.g. the environment variables. The override status with the final SCM values would naturally fit into this schema.

Rough idea:

```
$ bob show '//*[matchScm("overridden", "true")]' --fields=checkoutSCM
foo/bar-dev:
    checkoutSCM:
        overridden: True
        scm: git
        url: https://github.com/BobBuildTool/bob.git
```

**Comment by Ferruck** [comment]
This sounds sound and indeed more natural than querying the information from `bob status`. Do you already have a bit more concrete plans around this or is it still in its sketch phase?

**Comment by jkloetzke** [comment]
I never thought about it any deeper than that. But my gut feeling is that this going in the right direction. Basically the `show` command just shows the `Package` data structures. Any details that will come up during the implementation will most probably be about style rather than content.

The synthetic `override` SCM must be added but I find it not controversial. And the `matchScm` already exists.
