### ISSUE TITLE
Missing checkoutVars since Bob v0.17.0?

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#355]
It seems, that in the reworked step execution process done within v0.17.0 the `checkoutVars` (and `checkoutVarsWeak`) are not provided to the environment for the checkout step anymore.

We have a build process, where a required environment variable is set and provided to the checkout step via `checkoutVars`. This process worked with Bob v0.16.0, but is broken since v0.17.0.

The required environment variable is contained in the new _step.spec_ file, but is not contained in the step execution environment. To debug this, I modified Bob code to print `env` in `Invoker.__runCommand()` and can only see the variables from the whitelist.

Our platform for this build process is MSYS2/Windows.

Is this a bug?

**Comment by jkloetzke** [comment]
Hmm, sounds like a bug but it seems to work on Linux:

root.yaml:
```yaml
root: True
checkoutVars: [FOO]
checkoutScript: echo $FOO >&2
buildScript: "true"
packageScript: "true"
```

```
$ bob dev root -DFOO=bar
...
>> root
   CHECKOUT  dev/src/root/1/workspace 
bar
   BUILD     dev/build/root/1/workspace
   PACKAGE   dev/dist/root/1/workspace
Build result is in dev/dist/root/1/workspace
Duration: 0:00:00.140603, 1 checkout (0 overrides active), 1 package built, 0 downloaded.
```

Does this example above reproduce your problem on MSYS2? I currently have no Windows setup available.

**Comment by gruberchr** [comment]
It doesn't seem to be a problem in the execution environment of the custom build script, but in the `Scm.invoke()` function. In our case it's `SvnScm.invoke()`. We need environment variable `LANG` to be set on MSYS2/Windows for SVN checkout to avoid [character set conversion errors](http://svnbook.red-bean.com/en/1.7/svn.advanced.l10n.html#svn.advanced.l10n.svnuse).

**Comment by jkloetzke** [comment]
Oh, that changed, indeed. Before Bob 0.17 the invocation of the SCMs was generated into the checkout bash script. That's why they were executed in the same environment as the actual `checkoutScript`. Starting with Bob 0.17 the SCMs are called directly but without setting any variables. I'll have a look how to rectify this.

**Comment by jkloetzke** [comment]
Can you please test with the version in #356? I'll queue it for the next patch release of the 0.17 series then...

**Comment by gruberchr** [comment]
Ok, I tested our use case with your bugfix and it run successfully now again. So at least for this use case #355 seems to be fixed.
