### ISSUE TITLE
blackbox test not working inside venv

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#36]
When starting `test/run-tests.sh` from inside a venv and the system lacks some dependencies, the test fails.  This looks like the test is somehow not started inside the venv.

```
pip list | grep python-magic
```
is empty. Then entering the venv
```
source /.../pyvenv/bob/bin/activate
pip list | grep python-magic
```
returns the package name and version as expected. Now running `test/run_tests.sh` gives this error:
```
Run test/generator
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Traceback (most recent call last):
  File "/.../bob/pym/bob/scripts.py", line 98, in bob
    availableCommands[verb][1](argv, bobRoot)
  File "/.../bob/pym/bob/scripts.py", line 47, in __project
    doProject(*args, **kwargs)
  File "/.../bob/pym/bob/cmds/build.py", line 956, in doProject
    from ..generators.QtCreatorGenerator import qtProjectGenerator
  File "/.../bob/pym/bob/generators/QtCreatorGenerator.py", line 22, in <module>
    import magic
ImportError: No module named 'magic'
--- /dev/fd/63	2016-10-05 18:38:58.416804654 +0200
+++ output-plugin.txt	2016-10-05 18:19:31.212152069 +0200
@@ -0,0 +1,3 @@
+PLUGIN: root
+PLUGIN: []
+PLUGIN: ['--download=no']
test/generator failed
```

**Comment by kolewu** [comment]
Are you sure you don't have python-magic outside the venv? What is the result of the following outside the venv (use any needed package you want)?
```
python3 -c 'import magic'
```

And then maybe it's because I'm using the builtin `pyvenv` and not `virtualenv` (`pyvenv` is only available for python3, so inside the venv `python` and `python3` are equivalent):
```bash
pyvenv /tmp/bob
source /tmp/bob/bin/activate
pip install pyyaml schema
test/run-tests.sh
```

Same error as above, even on another computer.

**Comment by kolewu** [comment]
Is there something special about the generator? Because on this new computer, I don't have _PyYaml_ nor _schema_ outside the venv but it's only complaining about _magic_.

**Comment by kolewu** [comment]
There must be something special about the _magic_ package. If I insert `import schema` just before `import magic` the error is from not finding _magic_. But if I use non existing `import schema2` it complains about this ...

**Comment by jkloetzke** [comment]
Now I see the error too. This module seems to be _really_ special. I had to uninstall it from my normal installation (`pip3 uninstall python-magic`).

But this really seems to be related to how the test are working. Otherwise the module is functional. Outside the venv I get:

```
$ python3 -c 'import magic'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'magic'
```

Inside the venv it looks like its working:

```
(venv) jkloetzke@tuxedo:~/src/bob/bob$ python3 -c 'import magic'
(venv) jkloetzke@tuxedo:~/src/bob/bob$ 
```

In fact the qtcreator plugin actually works:

```
(venv) jkloetzke@tuxedo:~/tmp/foo$ bob project --list
qt-creator
(venv) jkloetzke@tuxedo:~/tmp/foo$ bob project qt-creator test-one/
>> test-one
   CHECKOUT  dev/src/test/1/workspace
   BUILD     skipped (unchanged input for dev/build/test-one/1/workspace)
   PACKAGE   skipped (unchanged input for dev/dist/test-one/1/workspace)
Build result is in dev/dist/test-one/1/workspace
>> test-one
   PROJECT   test-one/ (qt-creator)
(venv) jkloetzke@tuxedo:~/tmp/foo$
```

This triggers the import of the magic-module. So it does work. Well, except from inside run-tests.sh. I'm confused...

**Comment by kolewu** [comment]
Arrrrgh: As you can see, on the new computer, I haven't installed `python-magic` inside the venv.

With it installed, there only is an unexpected output from the shell script (see #38).

I have to find out, what's wrong with the other environment.

**Comment by kolewu** [comment]
Hmmm, so now you see the error but I no more :disappointed: What's wrong with the python world?

**Comment by jkloetzke** [comment]
:smile: I thought the same too. I will have a look at it tomorrow again. I'm out of ideas for today...

**Comment by jkloetzke** [comment]
Ok, found it. :smile: The error that I see is related to coverage3. It's installed on my host (but not inside venv!) and the tests are picking it up. If I edit run-tests.sh to _not_ use coverage3 then the test are running fine even inside venv. If I install the coverage module inside venv too then the tests are also fine with coverage enabled. Somehow the coverage instrumentation breaks this specific test when being installed on the host but not inside venv.

**Comment by kolewu** [comment]
I think it's because the shell doesn't know anything about the venv.  Maybe the tests should be made into pure python -- or coverage can be called as a python module.
