### ISSUE TITLE
scm: add support for mirrors

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#360]
This should support at least the following use cases:

* Setting up some preferred mirror location(s) that should be used *before* the actual location in the recipe. This is useful for corporate setups where an internal mirror absorbs most of the traffic.
* Adding fallback locations in case the primary location is unavailable.

Mirrors should probably only be used for deterministic SCMs. Otherwise the mirrors might not hold the same data.

**Comment by mahaase** [comment]
just a note, currently it is possible to overwrite the `GNU_MIRROR` environment variable in the project `default.yaml`.
that isn't a mirror-system, but it's cool! ;)
