### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by benjaminhampe** [BobBuildTool/bob#364]
% bob project -n qt-creator `<my-project-name>` -f ".*\.ui"

>> `<my-project-name>`
   PROJECT   `<my-project-name>` (qt-creator)
Build error: No kit found!
Run again with '--kit' and specify a kit or generate a Desktop kit, which is used by default.

The documentation of the meaning of the word "kit" or any hint about its application is a joke.

**Comment by jkloetzke** [comment]
Sure. Any help in form of pull requests is highly appreciated.

Those kits are Qt-Creator specific: https://doc.qt.io/qtcreator/creator-configuring.html#checking-build-and-run-settings It's the way how Qt-Creator handles toolchains. Looks like your installation does not have a default "Desktop" kit which should exist by default...

**Comment by benjaminhampe** [comment]
Sounds correct. Good hint. Its because there is no qt-creator on the system until i fixed my login credentials with qt.io. So thx.
I guess i will make a merge request regarding the documentation. Your answer of this question is what should stay in the docs.

**Comment by jkloetzke** [comment]
Cool. There is already a section for Qt-Creator in the man-page for `bob project` in `doc/manpages/bob-project.rst`. Maybe the error message should also give a hint too to find the relevant section in the manpage too...
