### ISSUE TITLE
git/url: add policy to ignore user name

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#368]
The user name is just for authentication. It does not change the content and should be ignored. Example:

    https://user@server.test/foo/bar

should be only hashed as

    https://server.test/foo/bar

to enable binary artifacts across users. The `~user` expansion must not be ignored because it changes the location and is therefore relevant. We need a policy because it will break the lookup of old artifacts.

**Comment by Ferruck** [comment]
I'm not sure if that's really an use-case, but what if the server sends different responses due to the username given?

**Comment by jkloetzke** [comment]
The main use case is gerrit. There you have to give your real user name to get access. With the current scheme nobody will be able to share binary artifacts.

But why would a git server give you a different content for the *same* location? I'm not aware of any git server that is capable of doing that. Of course you can certainly rewrite the URL with a reverse proxy but why would anybody do that?

**Comment by Ferruck** [comment]
> [...] gerrit.

> [..] why would anybody do that?

You see that? :wink: Honestly, it was just meant as a quick reminder that such systems may exist, personally I haven't heard of one, neither, and in general your proposal is a good idea.

**Comment by jkloetzke** [comment]
I think I'll add a note in the documentation that such moronic setups are not supported. :smiling_imp:  There are already other assumptions, e.g. that tags never change, that could be documentation too.
