### ISSUE TITLE
RFD: make shell easier to use

### ISSUE THREAD

**Issue by stefanreuther** [BobBuildTool/bob#37]
**What I want to do:** for debugging a build, I'd like to execute commands in the workspace. Could be `gdb`. Could be `make test`. Could be `make myfile.i`. Could be `./configure`. Right now, I have to figure out the workspace directory, and do something like `build.sh shell`. However, even if I do that, I'm still missing shell functions and most variables I defined in my recipes. Wouldn't it be nice to have a command like `bob shell <mypackage>`?

**Idea:** I made a prototype of a `bob shell` command (in perl, sorry; see attached file). Right now, this parses the `script` that bob places in each directory using some ad-hockery, and generates a new rcfile, which it then gives to an interactive bash. This shell has environment variables set and functions defined (the `script` is parsed up to the first line my ad-hoc parser does not understand, which is usually a command invocation).

**How could we do this in bob directly?** porting the perl to python would be trivial. A much better solution, however, would be to allow users to split setup and execution of a step. Instead of, say, buildScript, you specify buildSetup + buildScript. For building, both are concatenated to produce the same result as now. For the shell, just execute the buildSetup parts.

[bob-shell.txt](https://github.com/BobBuildTool/bob/files/511927/bob-shell.txt)

**Comment by jkloetzke** [comment]
Very good idea, indeed. I think parsing the scripts and applying these heuristics might work but looks brittle. Having direct support in Bob is definitely better.

I'll have to let it settle for the moment and think about it...
