### ISSUE TITLE
Specify minimum version of Git in the Documentation

### ISSUE THREAD

**Issue by Kalabaza** [BobBuildTool/bob#374]
A little detail that I think should be mentioned in the documentation of bob, is the minimum version of Git that is required to use with the tool.

With this specific SCM, in the latest release of bob (1.8) the default checkout behavior will use the option "--no-recurse-submodules", according to the release notes of Git, this option was "maybe" introduced not until version 2.13.0.

I'm not sure about this version, since it is not implicitly mentioned in the Git's release notes:

[2.13.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.13.0.txt#L145)
"git checkout" is taught the "--recurse-submodules" option.

Before the update to 1.8 I was using the version 1.7 and the version 2.7.4 of Git was working just fine.

**Comment by jkloetzke** [comment]
You're right. This needs to be documented properly. Also the history of the [man page](https://github.com/git/git/commit/1fc458d958be0e8347d7704933ae647afeabcd91) indicates that 2.13.0 introduced the switch.
