### ISSUE TITLE
Error in scanSubmodules of Git SCM

### ISSUE THREAD

**Issue by Kalabaza** [BobBuildTool/bob#375]
It seems I found a corner case for the submodules changes made to bob in the version 1.7.

In the [scanSubmodules](https://github.com/BobBuildTool/bob/blob/master/pym/bob/scm/git.py#L797) method, the existence of the file ".gitsubmodules" is checked but, was it considered that this file could be empty? (I don't even know if that file being empty is a valid use case?)

So, if the file ".gitmodules" is empty, the command to get the submodules will fail and the checkout is simply not completed (maybe the same will also happen in updateSubmodulesPost and statusSubmodule):

`Build error: Git audit failed: Command '['git', '-C', '.', 'config', '-f', '.gitmodules', '-z', '--get-regexp', 'path']' returned non-zero exit status 1`

Here is a sample of the output from the commands directly in the git repository:

```
$ ls -la | grep .gitmodules
-rw-r--r-- 1 user user    0 Nov 10 10:33 .gitmodules

$ git -C . config -f .gitmodules -z --get-regexp path

$ echo $?
1

$ git submodule add <fancy-module.git>
Cloning into ...

$ ls -la | grep .gitmodules
-rw-r--r--  1 user user  106 Nov 10 10:34 .gitmodules

$ git -C . config -f .gitmodules -z --get-regexp path
submodule.fancy-module.path
fancy-module^@

$ echo $?
0
```

**Comment by jkloetzke** [comment]
This is an error in the implementation. AFAICT it is valid that the file is empty. What I've overlooked is that the return value is 1 if "git config" does not find the key. Should be easy to fix by treating exit code 1 as valid.

**Comment by jkloetzke** [comment]
I think #377 should fix the problem. Could you please test it?

**Comment by Kalabaza** [comment]
That fix is working fine for me, now the checkout of that recipe works again.

**Comment by jkloetzke** [comment]
Cool. I'll merge and will eventually tag a 0.18.1 release...
