### ISSUE TITLE
Warning: cannot commit worspace state: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#376]
bob in MSYS2 said: 

`Warning: cannot commit worspace state: [Errno 13] Permission denied`

but i have no idea, what bob want to say to me :)

**Comment by jkloetzke** [comment]
Does it happen all the time?

The message says that the internal state could not be saved. This may lead to problems because Bob does not remember what he did on this invocation.

**Comment by mahaase** [comment]
Yep! it occures each time.

**Comment by sbixl** [comment]
Not sure if it is related to the same root cause but maybe i've encountered a similar problem (native windows): 
"Parse error: Error saving workspace state: [WinError 5] Zugriff verweigert: '.bob-state.pickle.new' -> '.bob-state.pickle'"

**Comment by jkloetzke** [comment]
Looks like you can only call `fsync()` on Windows if the file is opened for writing. On Unix there is no such requirement.

@sbixl I think your error is from an older version of Bob, right? It's a different problem where the state file (.bob-state.pickle) could not be replaced by the new state (.bob-state.pickle.new). If the problem persists I would recommend to open a new issue.

**Comment by mahaase** [comment]
error is gone! thx. 👍
