### ISSUE TITLE
provide var by tool and append new values

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#381]
Hi.

currently it is possible to provide paths in LD_LIBRARY_PATH by using libs in provideTools.
Now we need a solution to collect paths in PYTHONPATH (in our case) from different recipes. 
but this is currently not allowed: 

`Each environment variable must be defined only by one used tool.`

practically exactly the same like the LD_LIBRARY_PATH, but for different env-vars.
is this possible? 

BR.

**Comment by jkloetzke** [comment]
Unfortunately this is not possible at the moment. This sounds like you need something like the following:

```yaml
provideTools:
  foo:
    paths:
      PYTHONPATH: [ "lib/python3" ]
```

This may collide with regular `environment` definitions. Currently `LD_LIBRARY_PATH` is *always*  taken from `libs` and you cannot define it via regular `environment` definitions...

**Comment by mahaase** [comment]
we got a workaround, we are fine with.
i dont know, if this is a feature, bob should have.
its ur decision. feel free to close the request.

**Comment by jkloetzke** [comment]
Hmm, I'm not sure. It would be a generalization of `path` and `libs`. But let's wait until a real user is there...
