### ISSUE TITLE
parse error on commented lines

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#383]
```
root: True

buildScript: |
   # cp $<<not_existing_but_commented>> foo

packageScript: |
   true
```

```
$ bob ls
Parse error: No files matched in include pattern 'not_existing_but_commented'!
Processing stack: root.yaml
```

**Comment by rhubert** [comment]
```
diff --git a/pym/bob/input.py b/pym/bob/input.py
index 1d24b08..93913ac 100644
--- a/pym/bob/input.py
+++ b/pym/bob/input.py
@@ -1842,7 +1842,7 @@ class IncludeHelper:
 
     def __init__(self, scriptLanguage, fileLoader, baseDir, varBase, sourceName):
         self.__pattern = re.compile(r"""
-            \$<(?:
+            ^(?!\#).*\$<(?:
                 (?P<escaped>\$)     |
                 (?P<named>[<'][^'>]+)['>]>  |
                 (?P<braced>[<'][^'>]+)['>]> |
```

**Comment by jkloetzke** [comment]
The file inclusion syntax is independent of the actual scripting language. Doing it conditionally would require to have a non-trivial parser for each supported language. Even in your simple case the regex above would fail for

    A="#" B=$<<existing-file>> command

because it would incorrectly think that `$<<existing-file>>` is commented out.

**Comment by rhubert** [comment]
no this should work for your example if it's a one-line-build-scripts It didn't match if `text` starts with `#`.  I missed that the regex is applied to the whole script and not line by line. The `r.MULTILINE` might do the trick - but I'm unsure about the side effects.

```
diff --git a/pym/bob/input.py b/pym/bob/input.py
index 1d24b08..5c4435d 100644
--- a/pym/bob/input.py
+++ b/pym/bob/input.py
@@ -1842,13 +1842,13 @@ class IncludeHelper:
 
     def __init__(self, scriptLanguage, fileLoader, baseDir, varBase, sourceName):
         self.__pattern = re.compile(r"""
-            \$<(?:
+            ^(?!\#).*\$<(?:
                 (?P<escaped>\$)     |
                 (?P<named>[<'][^'>]+)['>]>  |
                 (?P<braced>[<'][^'>]+)['>]> |
                 (?P<invalid>)
             )
-            """, re.VERBOSE)
+            """, re.VERBOSE | re.MULTILINE)
         self.__resolverClass = scriptLanguage.Resolver
         self.__baseDir = baseDir
         self.__varBase = re.sub(r'[^a-zA-Z0-9_]', '_', varBase, flags=re.DOTALL)
```

And you're right commenting (multiple lines) in [bash](https://stackoverflow.com/questions/43158140/way-to-create-multiline-comments-in-bash) is possible using others than `#`-comments or the powershell's `<# #>` syntax is still broken. 

I just hit this and thought it might be easy to fix but it isn't :(
