### ISSUE TITLE
noUndefinedTools policy

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#385]
hi.

is there a way to filter a tool? e.g. buildTools: [lcov] --> if is linux [ARCH, or anything else].
we have classes which works for win MSYS2 and linux, than we check for the system (win/linux), e.g. by CMAKE_GENERATOR, and use the tool or not.

BR.

**Comment by jkloetzke** [comment]
No this is currently not supported. A viable workaround is to define a dummy tool in the Windows case.

In the long run we might introduce a syntax to conditionally require tools. I'm not sure how the syntax should look like, though.

**Comment by jkloetzke** [comment]
I'm currently not considering to add such functionality. It complicates things quite a bit internally and defining a dummy tool is not too hacky IMHO. Feel free to reopen if this feature is really required.
