### ISSUE TITLE
bob gets stuck

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#387]
```
bob_test$ bob dev root -j4 -vv

[   1] BUILD     baz-bootstrap - dev/build/baz-bootstrap/1/workspace
[   2] AUDIT     baz-bootstrap - dev/build/baz-bootstrap/1/workspace .. ok
[   3] PACKAGE   baz-bootstrap - dev/dist/baz-bootstrap/1/workspace
[   4] AUDIT     baz-bootstrap - dev/dist/baz-bootstrap/1/workspace .. ok
====== 0/4 jobs running, 9% (1/11 tasks) done 
 ****  <idle>
 ****  <idle>
 ****  <idle>
 ****  <idle>
```

[repocase.tar.gz](https://github.com/BobBuildTool/bob/files/5694753/repocase.tar.gz)

**Comment by jkloetzke** [comment]
This even deadlocks with `-j1`. :sob: Problem is understood but I have no idea yet how to solve it. That definitely has to be solved for the 0.18 train too...

**Comment by jkloetzke** [comment]
I'm still not sure if the proposed fix is the best idea but it solves the problem. I should probably add your test case too. It seems to work here but we should give it some more testing...

**Comment by rhubert** [comment]
This fixes the deadlock for my real world recipes :+1:
