### ISSUE TITLE
MSYS: BOB_DEP_PATHS including paths to src directory

### ISSUE THREAD

**Issue by daxcore** [BobBuildTool/bob#393]
I guess that is different to linux, is that correct for any reason?

```
+ BOB_DEP_PATHS=(['cmake::greeter-cross']='/home/daxcore-win/basement/tests/cross-platform/dev/src/cmake/greeter/1/workspace' ['cmake::libgreet-dev']='/home/daxcore-win/basement/tests/cross-platform/dev/dist/cmake/libgreet-dev/x86_64-pc-win32/1/workspace' ['cmake::libgreet-tgt']='/home/daxcore-win/basement/tests/cross-platform/dev/dist/cmake/libgreet-tgt/x86_64-pc-win32/1/workspace' ['cmake::libholler-dev']='/home/daxcore-win/basement/tests/cross-platform/dev/dist/cmake/libholler-dev/x86_64-pc-win32/1/workspace' ['cmake::libholler-tgt']='/home/daxcore-win/basement/tests/cross-platform/dev/dist/cmake/libholler-tgt/x86_64-pc-win32/1/workspace')
```

**Comment by jkloetzke** [comment]
Could you give a bit more context? What is different to Linux? What exactly is unexpected in the `BOB_DEP_PATHS` array?

**Comment by daxcore** [comment]
the paths to `/dev/src/` directories, isn't it unexpected?

**Comment by jkloetzke** [comment]
No, not if you're in the build step and the package has a checkout step defined. The key in `BOB_DEP_PATHS` will be the package name that is currently built. Likewise the package step will have a reference to it's own `dev/build/...` directory. In both cases this will be the same as `$1`.

I was confused by the MSYS and Linux in the description. This behaviour is independent of the OS.

**Comment by daxcore** [comment]
thanks!
