### ISSUE TITLE
unknown issue in MSYS2 with MinGW64

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#396]
I started MSYS2 with the MinGW64 toolchain:

```
bob show -f scriptLanguage amd64::windows/
Error: Invalid syntax: Expected end of text, found ';'  (at char 5), (line:1, col:6)
Offending query: amd64;windows\
                       ^.-- Error location
```

**Comment by jkloetzke** [comment]
That's MSYS playing tricks with you. There are some sophisticated heuristics to convert arguments between the POSIX and Windows world baked into MSYS. In this case MSYS thinks you gave a path list and converted the argument to a Windows path list.

**Comment by daxcore** [comment]
Thanks, I will try to workaround.

**Comment by daxcore** [comment]
solution: a workaround is: `bob dev //foo::bar/libs::recipe`

**Comment by daxcore** [comment]
But it is not possible to use bob with mingw so far!
