### ISSUE TITLE
[improvement] root-recipe filter

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#403]
what do u think bout a root-recipe filter e.g. by the `BOB_HOST_PLATFORM`.

`bob ls` shows all root-recipes, also the one, not possible to use. msys stuff will not work in linux and linux-stuff will not work in msys.

```
root: True
rootFilter: "$(eq,$BOB_HOST_PLATFORM,msys)"
```

**Comment by jkloetzke** [comment]
How about making the `root` attribute a string/if-expression directly?

```yaml
root: "$(eq,$BOB_HOST_PLATFORM,msys)"
```

or 

```yaml
root: !expr |
    "$BOB_HOST_PLATFORM" == "msys"
```

**Comment by mahaase** [comment]
perfect!
