### ISSUE TITLE
Bob release 0.19.0

### ISSUE THREAD

**Issue by danielroedl** [BobBuildTool/bob#404]
Will there be a new release (0.19.0) in the near future? It would be nice if this is planned along in the near future.

**Comment by jkloetzke** [comment]
Yes. I've created a [0.19](https://github.com/BobBuildTool/bob/milestone/6) milestone to track what should go into the next release. I hope to cut a release candidate in roughly two weeks from now.

**Comment by jkloetzke** [comment]
[Bob 0.19.0-rc1](https://github.com/BobBuildTool/bob/releases/tag/v0.19.0-rc1) was just released. :)

**Comment by jkloetzke** [comment]
I'll release the final version in two weeks from now unless some major issues are found...
