### ISSUE TITLE
PyPi Release 0.18.1 is missing python 3.6 and 3.7

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#407]
The [travis build](https://travis-ci.org/github/BobBuildTool/bob/builds/743011496) for 0.18.1 has errors for python 3.6 and 3.7 and so the corresponding wheels are missing from [PyPi repository](https://pypi.org/project/BobBuildTool/0.18.1/#files).

**Comment by jkloetzke** [comment]
I tried to re-run the tag build but because the API token had to be refreshed (Codecov had a security breach) the upload fails. I think there is not much that we can do about it. :disappointed:
