### ISSUE TITLE
install error: 'zsh: no matches found: [--user]'

### ISSUE THREAD

**Issue by benomatis** [BobBuildTool/bob#409]
on macOS 11.3 running `python3 -m pip install BobBuildTool [--user]` gives error  `zsh: no matches found: [--user]`, tried replacing `user` with my actual username, failed with the same error, tried ommitting `[--user]` altogether, failed again with `no previously-included directories found matching 'docs/_build'.`

**Comment by jkloetzke** [comment]
The `[--user]` option is meant as optional argument: either leave it out to install the package globally or supply `--user` to install into the users home directory. See https://packaging.python.org/tutorials/installing-packages/ for more information.

But about the build failure: could you please paste the error log? The installation was never tested on macOS so there is a high chance that something is wrong in setup.py...

**Comment by benomatis** [comment]
Sorry, this was related to https://github.com/stripe/stripe-react-native/issues/174 (it's a private repo at this moment, will be published later, not sure if these issues will ever be published though), and I missed a step in their documentation.
