### ISSUE TITLE
pwsh: The AsByteStream parameter is only available from version pwsh 6.0.

### ISSUE THREAD

**Issue by sbixl** [BobBuildTool/bob#412]
Hi,

the issue is about the following line in the file languages.py:

https://github.com/BobBuildTool/bob/blob/da7d5b283863de3493d01caba4dcea8c1b4d447d/pym/bob/languages.py#L421

Because the windows 10 distribution does only come with pwsh version 5.x, the execution will fail because the parameter "AsByteStream" is unknown. AFAIK there is no plan to update the version from 5.x to a higher one.

If you use: ` self.prolog.append("'@) | Set-Content {VAR} -Encoding Byte".format(VAR=var))` it works fine.

Is it possible that we remain backward compatible to pwsh version 5.x at this point?

Regards
Sebastian

**Comment by jkloetzke** [comment]
Hmm, it looks like that `-Encoding Byte` was removed in PowerShell 6.0. The current documentation does not list it either: https://docs.microsoft.com/de-de/powershell/module/Microsoft.PowerShell.Management/Set-Content?view=powershell-7. Any other idea how? My experience with PowerShell is unfortunately quite limited...

**Comment by sbixl** [comment]
Maybe we can use: https://docs.microsoft.com/de-de/dotnet/api/system.io.file.writeallbytes?view=net-5.0

I have briefly checked it (with pwsh version 5):

```
def _includeFile(self, content):
        var = "$_{}{}".format(self.varBase, self.count)
        self.count += 1
        self.prolog.extend([
            "{VAR} = (New-TemporaryFile).FullName".format(VAR=var),
            "$_BOB_TMP_CLEANUP += {VAR}".format(VAR=var),
            "$decode = [Convert]::FromBase64String(@'"])
        self.prolog.extend(sliceString(b64encode(content).decode("ascii"), 76))
        self.prolog.append("'@)")
        self.prolog.append("[io.file]::WriteAllBytes( {VAR}, $decode )".format(VAR=var))
        return var
```

**Comment by jkloetzke** [comment]
Could you please try #413 and see if this works on pwsh 5 too?

**Comment by sbixl** [comment]
Works perfectly! :-)

Is it possible to create a new release with this bug fix?

**Comment by jkloetzke** [comment]
Sure. I'll queue it for 0.19.2...
