### ISSUE TITLE
MSYS2: unzip error

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#414]
https://github.com/BobBuildTool/bob/blob/30b1fdfc9dca9e40f46a102f06ac7217365c93c1/pym/bob/scm/url.py#L158-L161

hey,

bob can not extract the file https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip. 

MSYS2/python
```
+ python -m zipfile -e graphviz-2.44.1-win32.zip .
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/zipfile.py", line 2441, in <module>
    main()
  File "/usr/lib/python3.8/zipfile.py", line 2413, in main
    zf.extractall(curdir)
  File "/usr/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.8/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'Graphviz\\bin\\acyclic.exe'
Error: Recipe devel::win::graphviz, layer basement in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip failed
Error: Command 'python -m zipfile -e graphviz-2.44.1-win32.zip .' returned exit status 1
```
and MSYS2/unzip 
```
warning:  graphviz-2.44.1-win32.zip appears to use backslashes as path separas
Error: Recipe devel::win::graphviz, layer basement in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip failed
Error: Command 'unzip -o graphviz-2.44.1-win32.zip' returned exit status 1
```
will fail with a backslash issue.

btw: MSYS2/p7zip will also not work (i added it to bob temporary):
```
Error: Recipe devel::win::graphviz, layer basement in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip in checkoutSCM: dir:., url:https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/graphviz-2.44.1-win32.zip failed
Error: Command '7z x -y graphviz-2.44.1-win32.zip' returned exit status 2
```

It looks like, the graphviz zip is just extractable by a native tool. native 7z or embedded windows ziptool (by explorer) will work.

i don't know a open-source unzip native windows tool.

any ideas to fix this?

**Comment by sbixl** [comment]
Hi Martin, you can use the command line tool version of [7z](https://github.com/kornelski/7z). You can build if from source and provide it as tool. 

Please feel free to use the attached recipe building 7z with pwsh for native windows: [7z.zip](https://github.com/BobBuildTool/bob/files/6502664/7z.zip)

The recipe is part of the [native windows basement project](https://github.com/sbixl/bob.native.windows.basement) which I will push at the end of this week.

**Comment by jkloetzke** [comment]
It looks like this archive does not conform to the specification. Additionally `unzip` exits with return code 1 because of the warning but is otherwise able to extract the archive. We could theoretically treat return code 1 of unzip as "success" but the manpage says:

> 1  one or more warning errors were encountered, but processing completed successfully anyway.  This includes zipfiles where one or more files was skipped due to unsupported compression method or encryption with an unknown password.

Reading this I would not like to treat code 1 as "success". I'm tentatively against adding some workaround for such broken archives. As a workaround you could:

```yaml
checkoutSCM:
  scm: url
  url: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/2.47.1/stable_windows_10_msbuild_Release_Win32_graphviz-2.47.1-win32.zip
  extract: False

checkoutDeterministic: true
checkoutScript: |
  unzip -o *.zip || test $? -eq 1
```

Even the latest zip file is broken. :( I guess opening an issue on https://gitlab.com/graphviz/graphviz couldn't hurt...

**Comment by mahaase** [comment]
https://gitlab.com/graphviz/graphviz/-/issues/2077

ticket created.

also added a PR in basement as workaround:

https://github.com/BobBuildTool/basement/pull/86
