### ISSUE TITLE
Bob minimum version is checked too late

### ISSUE THREAD

**Issue by danielroedl** [BobBuildTool/bob#420]
Hi,

there is a problem with the config.yaml in context of changes between bob versions. 
If there is a new key in the config.yaml or another incompatible change (new policy, struture change) in a new  bob version the error is not pointing to the wrong number.

With not known policies the error is (there is a hint to the bob version):
`Parse error: Error while validating config.yaml: Invalid policy specified! Maybe your Bob is too old?`

With new keys the error is just:
`Parse error: Error while validating config.yaml: Wrong key 'Test123' in {'Test123': true, ...`

Would it be better to first check the `bobMinimumVersion` and than validate the everything else?

**Comment by jkloetzke** [comment]
I think this makes sense. It will make parsing a bit more difficult but the better error message looks worth it.
