### ISSUE TITLE
strange behavior if same checkoutSCM dir: is used multiple times

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#424]
Hey, 

a college got the following finding:

> If you have 2 recipes configured with the same `checkoutSCM dir:` you will get both results after performing a build of one of the recipes.
> Example:
> Assume you have `r1.yaml` which builds r1.exe and `checkoutSCM dir:` is set to `directory.r`. The second recipe `r2.yaml` builds r2.exe but it use the same `checkoutSCM dir:` `directory.r`.
> When bob successfully built r1 the result of building r2 is r1.exe and r2.exe.

**Comment by jkloetzke** [comment]
Any chance to supply some minimal recipes that exhibit the problem? I don't yet understand the issue...

**Comment by mahaase** [comment]
i also tried to reproduce this. not possible so far. lets close this ticket. we will reopen it, if there is a problem, and we have a reproducable example.
