### ISSUE TITLE
environment handling behavior

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#426]
hey,

is it a bug, or do i still misunderstand the `environment` handling.

if there is a variable in `default.yaml` like `BASEMENT_OPTIMIZE` which will change the `target-toolchain` of `cross-toolchain.yaml`.
then i have my chain of recipes:

recipe.yaml:
```
inherit: [rootrecipe]

depends: 
  - another::recipe
```

another/recipe.yaml:
```
environment:
  BASEMENT_OPTIMIZE: "<something-else-than-default>"

buildSc....
```

so the override of the variable will not effect the target-toolchain. isn't the deepest recipe the one, with the highest priority?
isn't the stuff in `environment` globally and parsed completely at the beginning of the build?

that was my understanding of `environment`. scoped stuff can be done by `privateEnvironement`, `provideVars` and `use: [environment]` a.s.o. i.m.o.?!

**Comment by jkloetzke** [comment]
The principle environment operation is described here: https://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#environment-handling. You're right that every recipe can override the inherited environment.

But for string substitutions it might not be obvious when they happen. In principle this happens eagerly. In particular the variables in `provideVars` and `provideTools` are substituted when the package is calculated. Every dependency that uses the provided variable or tool will see the final string.

Given the current basement recipes it is therefore not possible to override `BASEMENT_OPTIMIZE` in a meaningful way deeper in the dependency hierarchy. This variable influences the CFLAGS but it is only once substituted when the Toolchain package is calculated. The CFLAGS are then a static string for all consumers.

**Comment by daxcore** [comment]
i found a good solution to provide the enduser a easy way to get debug/release builds by using the `bob dev -c config` file.  but the config file isn't supported by jenkins plugin, is it?

what is the best way to provide a debug and a release variant of the same project?

**Comment by jkloetzke** [comment]
The Jenkins commend does support the configuration files but it has to be used before the subcommand: `bob jenkins -c config ...`...

**Comment by jkloetzke** [comment]
I think there is no real problem here. Feel free to reopen if you think otherwise.
