### ISSUE TITLE
bob project vs2019 creates invalid files

### ISSUE THREAD

**Issue by sschleic** [BobBuildTool/bob#448]
With the current master `bob project vs2019` generates invalid files.
 Currently every file generated by bob starts with an empty line (.sln) or with an \ (.vcxproj). This causes error while opening the project with visual studio.
I investigated the code and found commit ea36ae4912c is causing the problem.

Solution should be (VisualStudio.py, line45):
`SOLUTION_PROJECT_TEMPLATE= r"""Project("{{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}}") = "{NAME}", "{NAME}\\{NAME}.vcxproj", "{{{GUID}}}"`

VisualStudio.py, line41:
`PROJECT_TEMPLATE = r"""<?xml version="1.0" encoding="utf-8"?> `

similar for all other template definitions.

**Comment by jkloetzke** [comment]
Thanks for the report. Could you test #449 and see if this fixes the problem?

**Comment by sschleic** [comment]
https://github.com/BobBuildTool/bob/pull/449 solves the problem about visualStudio project files generation. Project can be opened with Visual Studio 2019 as expected.
