### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by Kalabaza** [BobBuildTool/bob#470]
So, I was using bob today to build a "fancy project" and bam, I ran out of space and everything was just cancelled at once:

```
bob dev fancy/project -j6
...
Parse error: Error saving workspace state: [Errno 28] No space left on device
```

The problem is that after this event I was not able to build the software anymore (seems that a dictionary was corrupted):

```
bob dev fancy/project -j6 -vvv
...
Parse error: Error loading plugin plugins/fetch-information.py: Parse error: Error decoding workspace state: pickle data was truncated
```

So, thinking that I could solve the problem, I try deleting the file .bob-state.pickle but then everything just got worse:

```
bob dev fancy/project -j6 -vvv
...
New SCM checkout 'package' collides with existing file in workspace 'dev/src/someplace/workspace'!
```

Seems that I will have to start over from a clean workspace since I have corrupted everything, if I remove a colliding folder then a new one is found, so the question here is:

What can be done to solve this issues in the future or at least mitigate in the correct way?

**Comment by jkloetzke** [comment]
Actually this should not have happened. There seems to be a bug in the state handling. The intention was that there is always a valid state, at least from the previous invocation. Obviously there is a bug that still corrupts the whole state. :(

**Comment by jkloetzke** [comment]
Thanks for the report!
