### ISSUE TITLE
"Error loading audit" not visible if verbosity is to low

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#472]
Not sure if it works as designed or if it's a Bug:

If the `stepAction`s severity is lower than the verbosity a `DummyTUIAction` is created. If `fail` us used on this step the error is not shown. 

I noticed this when I was looking for a `audit.json.gz` which wasn't generated for unknown reason. After unsing `bob dev -v` the "Error loading audit" was shown for the dependency but it took me some time to figure that out. Maybe there are other code paths where this could happen as well?

IMO `step.fail()` should always be shown?

**Comment by jkloetzke** [comment]
It more or less works as intended but given this example it is really confusing. The intention of `stepAction` is to inform the user about something that takes a longer time. So the tty code prints something if the action starts and then the result once its finished. If the severity is too low, no start information is printed and it (currently) makes no sense to print the result either.

I guess we have to change it to still output the result if the severity of the result is higher than the initial severity of the `stepAction`. It will require some extra output formatting but just dropping the `a.fail(e.slogan, WARNING)` is indeed confusing.
