### ISSUE TITLE
cutted fingerprint print

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#478]
https://github.com/BobBuildTool/bob/blob/223f4a595ed8b58660b0cd3286dbb66ba1c69266/pym/bob/cmds/build/builder.py#L1774

`FNGRPRNT  devel::parasoft-cpptest .. 'x86_64\nmsys-2.0/19.3003.5\nx86_64\nlib...`

could we remove this limiter or what's the reason for that? important information are unvisible.

**Comment by jkloetzke** [comment]
The rationale was that the output of the fingerprint script could be arbitrarily long and usually does not matter to the user. But I share your concern that it's hard to debug if the fingerprint script output needs to be examined as a whole. I guess we should display it when compiling with "-vv"...
