### ISSUE TITLE
Error while trying to mount directory during the checkout step

### ISSUE THREAD

**Issue by frajasalo** [BobBuildTool/bob#479]
We have a class that uses `checkoutDep: True`. When our project is build bob downloads this dependency from archive:

    PACKAGE   skipped (already downloaded in work/ext/autoconf-archive/aarch64-linux-gnu/dist/2/workspace)

When the recipe that uses this class is checked out we get an error that bob can't mount the workspace. But bob wants to mount its `build` directory and not the `dist`:

```
src/namespace-sandbox/namespace-sandbox.c:547: cannot mount '/path/to/recipes/work/ext/autoconf-archive/aarch64-linux-gnu/build/2/workspace' on '/tmp/tmp0r3btqqp/bob/4d28a660b06a15c4db54ad27bcd838cbee9ace6f/workspace': No such file or directory
```

**Comment by jkloetzke** [comment]
I think I found the culprit. Could you give it a thorough testing?
