### ISSUE TITLE
An internal Exception has occured. This should not have happenend.

### ISSUE THREAD

**Issue by tungphampcc** [BobBuildTool/bob#48]
After i typed this command: 'bob ls', an exception occurred. So i open an issue at https://github.com/BobBuildTool/bob as required with the following backtrace:

**Traceback** (most recent call last):
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 98, in bob
    availableCommands[verb][1](argv, bobRoot)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 42, in __ls
    from .cmds.misc import doLS
  File "/home/user/BobBuildTool/pym/bob/cmds/misc.py", line 19, in <module>
    from ..input import RecipeSet, walkPackagePath
  File "/home/user/BobBuildTool/pym/bob/input.py", line 412, in <module>
    class GitScm:
  File "/home/user/BobBuildTool/pym/bob/input.py", line 414, in GitScm
    SCHEMA = schema.Schema({
AttributeError: 'module' object has no attribute 'Schema'

**Comment by rhubert** [comment]
You need to install schema. See documentation/getting started.

Am 18. Oktober 2016 18:21:41 MESZ, schrieb tungphampcc <notifications@github.com>:
>After i typed this command: 'bob ls', an exception occurred. So i open
>an issue at https://github.com/BobBuildTool/bob as required with the
>following backtrace:
>
>**Traceback** (most recent call last):
>  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 98, in bob
>    availableCommands[verb][1](argv, bobRoot)
>  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 42, in __ls
>    from .cmds.misc import doLS
>File "/home/user/BobBuildTool/pym/bob/cmds/misc.py", line 19, in
><module>
>    from ..input import RecipeSet, walkPackagePath
> File "/home/user/BobBuildTool/pym/bob/input.py", line 412, in <module>
>    class GitScm:
>  File "/home/user/BobBuildTool/pym/bob/input.py", line 414, in GitScm
>    SCHEMA = schema.Schema({
>AttributeError: 'module' object has no attribute 'Schema'
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BobBuildTool/bob/issues/48

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jkloetzke** [comment]
The current version already has a graceful check included:

```
(venv) jkloetzke@tuxedo:~/src/bob/playground/recipes$ bob ls
Python module 'schema' seems to be missing. Please check your installation...
```

As Ralf wrote, following the getting started guide should get you, well, started... :wink:
