### ISSUE TITLE
scm import not working while building in out-of-source-tree

### ISSUE THREAD

**Issue by sbixl** [BobBuildTool/bob#489]
While building in a out-of-source-tree directory, the path to the scm import(s) (of the master project) are not adapted.

Please use the attached [repo.case.zip](https://github.com/BobBuildTool/bob/files/9646505/repo.case.zip) and do the following steps for reproducing it:

`bob init . test_build`
`cd test_build`
`bob dev test`

Bob fails with:

>> test
   CHECKOUT  dev\src\test\1\workspace
Error: Cannot import 'recipes/patches': not a directory!
Error: Recipe test in checkoutSCM: dir:patches, url:recipes/patches in checkoutSCM: dir:patches, url:recipes/patches failed
Build error: .\dev\src\test\1\checkout.cmd returned with 1

**Comment by jkloetzke** [comment]
Thanks for the report. Should be fixed in master...
