### ISSUE TITLE
latest sphinx version breaks pip install

### ISSUE THREAD

**Issue by kaiehrhardt** [BobBuildTool/bob#515]
# error
ModuleNotFoundError: No module named 'sphinx.setup_command'

# test env docker
```Dockerfile
FROM python:3
RUN pip install --upgrade pip && \
    pip install sphinx && \
    pip install -v BobBuildTool
```

# root cause
https://github.com/sphinx-doc/sphinx/pull/11363

# tmp fix
```Dockerfile
FROM python:3
RUN pip install --upgrade pip && \
    pip install sphinx==6.2.1 && \
    pip install packaging==20.9 && \
    pip install -v BobBuildTool
```

**Comment by rhubert** [comment]
Same as #513 ?

**Comment by kaiehrhardt** [comment]
I was not sure if this is really the same problem. It's a similar error pattern at different times. Just wanted to share my findings on this. In addition it is present in every python version.

**Comment by jkloetzke** [comment]
Thanks for the report. Unfortunately Bobs installation process heavily relies on `setup.py`. This will require some larger refactoring I guess....

**Comment by kolewu** [comment]
Better: build the PyPi package for python 3.11 then there is no need to build it locally and sphinx is no longer needed!

**Comment by jkloetzke** [comment]
Should be fixed by #516

**Comment by kolewu** [comment]
Could you please push a new 0.22.0 release with python 3.11 wheel to pypi? Then at least the build problem is fixed with a workaround, because no local build is necessary and the sphinx problem thus not triggered.

**Comment by jkloetzke** [comment]
Sure, can do that. I'd wait for #517 to be merged, though...
