### ISSUE TITLE
completion broken for zsh

### ISSUE THREAD

**Issue by martinkriegel** [BobBuildTool/bob#52]
Since the "bash-completion: handle colons in COMP_WORDBREAKS"-commit in contrib/bash-completion its broken for zsh:

martin@kriegel ~/mib3/tsd-recipes-mib3 (git)-[master] % bob dev zr3/__bob:5: command not found: _get_comp_words_by_ref
__bob:9: command not found: __ltrim_colon_completions

**Comment by jkloetzke** [comment]
Either zsh provides some comparable helper functions or we have to replicate these functions in the bob bash completion...

**Comment by rhubert** [comment]
@martinkriegel  please test the fix from 3123649
