### ISSUE TITLE
Build steps can get finished with large delay in multi job mode

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#539]
If Bob runs in multi job mode (with option `-j`), task scheduling is active, which currently (Bob v0.23) has some unexpected side effects.

When the script of a build step is finished, this is indicated on the TTY interface by shifting the corresponding line
```
[    ] BUILD ...
```
from the stage of running jobs to the stage of finished jobs. However, this only shows that the task for running the build script has finished, but not the complete build step. To finish the build step, the audit trail has to be generated at the end (unless Bob is invoked with `--no-audit`). This is an independent task, indicated on the TTY interface with a separate line
```
[    ] AUDIT ...
```

Currently the tasks for audit trail generation are first scheduled after all build scripts that can be executed independently. In a configuration with many independent and long running build steps, this can be very late. Moreover this means that each of these independent build steps only finishes after all the other build scripts have finished and the tasks for audit trail generation have run.

This has at least the following observed side effects:

1. When the build process is cancelled and resumed with option `--resume`, the complete build step is restarted, if the audit trail generation task did not run yet, even when the build scripts were already finished. This can be very annoying in large builds with long running build scripts.
2. The progress indicator, which shows the number and percentage of done tasks is updated too late. It is first updated, when the build step is finished and not the build script.

**Comment by jkloetzke** [comment]
Thanks for the detailed report. I'll look into it. Because this touches the core build logic it won't be an easy fix, though.

**Comment by jkloetzke** [comment]
It took a bit longer than anticipated but the attached PR should hopefully fix the problem. Please give it a try on your side...

**Comment by gruberchr** [comment]
Commit 7228fb7 seems to fix this issue.

**Comment by jkloetzke** [comment]
Thanks for testing.
