### ISSUE TITLE
metaEnvironment does not seem to support var substitution

### ISSUE THREAD

**Issue by sixtyfourktec** [BobBuildTool/bob#573]
Something like this is not possible right now:
```
metaEnvironment:
       PKG_VERSION: "$LINUX_VERSION"
```
If we have generic recipes which e.g. get the version number to be used passed in, it would be nice if this is also reflected in the PKG_VERSION. I guess this would be the main place someone would like to look at for this kind of information.

**Comment by rhubert** [comment]
I can't remember why we decided not to substitute this. It's also not mentioned in the [PR](https://github.com/BobBuildTool/bob/pull/122) :thinking: @jkloetzke can you remember?

As I also have this use-case and don't see a good reason against I think this could be supported.

**Comment by jkloetzke** [comment]
IIRC we thought that it's not necessary because the meta environment should describe static properties of the recipe/package. Apparently this assumption simply does not hold. So I guess we should just add the substitution support and let it behave like `privateEnvironment`.
