### ISSUE TITLE
layers: backwards compatibility for nested layers 

### ISSUE THREAD

**Issue by sbixl** [BobBuildTool/bob#595]
First of all, thanks to all contributers for providing the great feature of the managed layers. 🙂

**Describe the bug**
It looks like Bob is no longer able to recognize nested layers based on git submdolues. This would be a very unfavorable behavior as older projects would then be dependent on the Bob version. Is this the desired behavior? 

**Steps to reproduce**
1. Run `bob ls` in a project where layers are based on git submodules. The project must contain one layer with a nested layer. 
2.  Parser error: Layer 'basement' does not exist! 

**Context**
- OS: [Windows 10]
- Bob version [0.25.rc1]
- Python version [3.11.9]

**Comment by jkloetzke** [comment]
Indeed, nested layers have been removed when managed layers were added. I was hoping that layer nesting has never been used and that its possible to drop them without a backwards compatibility policy. Looks like I was wrong. :sweat_smile: Anyway, I think we have a couple of options here:

1. Add a policy that either keeps the old layers behaviour (nesting, not managed) or the current behaviour (no nesting, managed). This is probably the easiest option but would rule out nested, managed layers.
2. Add a policy that just disables nested layers. So if the policy is on the old behaviour, the traditional nesting is used. It's still possible to use managed layers as sub-layers.
3. Don't do it as a policy but add a regular option to control nesting. I would only do that if there is a real, hard use case for that, though.

In the long run, I would get rid of nested layers because they were a simple but bad idea. More often than not, layers form a DAG and not a tree. But if there is a use case for nesting then of course we can rethink that decision. Let me know what you think.

**Comment by sbixl** [comment]
I am also not friend of nested layers and completely agree with your last sentence.

**Use case:**

The only reason why we use the nested layer feature is that you have to change the nested layer centrally in one place and then automatically deploy it via the parent layer.

Imagine the following use case where several projects are being developed at the same time in paralell. All this projects depends on a bob layer which contains shared software libraries. This layer is very special and is only used for certain products. 
Parallel to this, there are other projects who basically only need the usual tools (e.g Ninja, CMake, Toolchains, ...) as dependency. In order to keep the administration effort to a minimum, there is therefore a basement layer that only provides tools. This layer shall be used by any project regardless of whether it is a e.g firmware, python or windows project

The basement layer is therefore a mandatory dependency of the layer which contains the speical software libraries too. For the maintainer who manages this layer, it is the easiest way to anchor the basement layer as a nested layer as this always ensures that the two layers fit together. Furthermore, the projects that use this layer only have to update the main layer and automatically pull the basement layer status specified by the maintainer. But the real reason is that the higher-level layer also contains packages that can be built standalone. These can be, for example, unit tests that have to be built independently of the project recipes (for example in the CI but also locally).

That was quite a lot of prose... I hope it's halfway understandable what I mean. 😅

If I think about it further, the use of at least one nested layer is not so far-fetched. Unless there is a better alternative that I haven't thought of yet?

**Comment by rhubert** [comment]
Well, this kind of nesting is still supported. If I understood you correctly you have something like this in you project's `config.yaml`:

```
layers:
  - common
```

and in the `common` layer:

```
layers:
 - libs
 - basement
```

This is still supported. The only thing that changed is the way of how the layers are placed / expected in the filesystem.

Old:
```
project/layers/common/layers/basement
project/layers/common/layers/libs
```

New:
```
project/layers/common
project/layers/basement
project/layers/libs
```

To use bob 0.25 on a old project I think you'll only have to add some symlinks?

**Comment by sbixl** [comment]
This is exactly the use case in a nutshell. ;-) 

It would be nice if Bob could recognize this in some way and “bend” it to the new concept. A symlink would be a possibility, but the “Symlink” feature must be explicitly activated on Windows. There may be security guidelines in e.g companies that prohibit this.

Could it be recognized via the setting  [bobMinimumVersion](https://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#bobminimumversion). I guess all projects that use the manged layers should upgrade this setting to version 0.25?

Regardless of this, we will switch completely to managed layers as soon as version 0.25 is released.

**Comment by jkloetzke** [comment]
I guess this boils down to option one. We add a policy that restores the old behaviour for existing projects. Starting with Bob 0.25,  the new behaviour of the policy allows managed layers and expects them in the new, flat directory layout.

**Comment by rhubert** [comment]
@jkloetzke do you have time for this? Otherwise I'd give it a try...

**Comment by jkloetzke** [comment]
I did already start on this but I am travelling the whole week. I should be able to finish that by the end of the week, hopefully.

**Comment by sbixl** [comment]
I have tested the new policy and it now works as desired. Many thanks for that! :-)

However, I have noticed one more point. If you configure a managed layer and do not specify the `commit` property, the default branch is always checked out. 

AFAIK, we had discussed that a layer should always have a fixed commit or tag.  Is that still the case ?

In the following example I would have expected Bob to report an error and point out that the layer is not sufficiently configured.

```
bobMinimumVersion: "0.24"
scriptLanguage: PowerShell

policies:
    managedLayers: True
    defaultFileMode: False

layers:
    - name: basement
      scm: git
      url: git@<some_url>/basement/recipes.git
```

**Comment by jkloetzke** [comment]
> I have tested the new policy and it now works as expected. Many thanks for that! :-)

Nice. Thanks for testing.

> However, I have noticed one more point. If you configure a managed layer and do not specify the `commit` property, the default branch is always checked out.
> 
> AFAIK, we had discussed that a layer should always have a fixed commit or tag. Is that still the case ?

Hmm, I think we never settled to make this a hard requirement. Sure, its probably a good idea to use a commit/tag for managed layer. But do we really need to make this a hard requirement and don't let the user choose a branch instead? I wouldn't rule out that this could have its application in some environments.

OTOH, managed layers now behave the same like SCMs in recipes. That way, it's the least surprising to users IMHO.

**Comment by sbixl** [comment]
No, that's not a problem at all. The layer handling, as it is now, is much better than using gitsubmodules before. There you had to update the commit every time. This is quite annoying, especially when a layer is spread over several projects. If the old behavior as with the GitSubmodules is desired, thr user can simply implement this via the `commit` property.

I just wanted to make sure that the "new" feature is really wanted that way.

**Comment by jkloetzke** [comment]
Thanks. I'll merge the PR. I just noticed that we forgot to include the managed layers in the audit trail, though. :see_no_evil:  Since there are `layersScmOverrides` and "floating" managed layers, this is an important gap that should be addressed before the final release I guess...
