### ISSUE TITLE
developNamePersister hook is not documented

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#65]
The hook `developNamePersister` that was introduced in 6a6baa94b65262c0dc904bce834d68e2549682bf is not documented.

**Comment by rhubert** [comment]
Do you have a specific question or would something like 

> In addition to the formatters you can hook the developNamePersister. This persisters holds all variants and the path in which the step is processed. The default implementation in Bob is to append the path returned by the developNameFormatter by a incrementing number starting by one for each variant. If your nameFormatter generates unique names for each variant of the packages you may want to override the perisiter to change this behavior, e.g. do not add a number for the first variant.

appended to Path formatter hooks fit your needs?

**Comment by jkloetzke** [comment]
I'm almost finished with that chapter. I'll create a pull request when finshed...
