### ISSUE TITLE
Add info about active scmOverrides

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#99]
Currently there is no way to tell if an 'scmOverride' matched and what has been changed. Maybe extend "bob query-scm"?

**Comment by rhubert** [comment]
I think extending 'bob query-scm' is basically a good idea, but maybe it's not used without a hint that scmOverrides are active. What about a build-summary?

```
Build result is in dev/dist/root/1/workspace
- Build time: 1d 2h 3m 4s
- packages build: 42 downloaded: 123
- active scmOverrides for packages: a,b,c,d
```

After #100 is implemented the shared packages could also be shown.

**Comment by jkloetzke** [comment]
I really like the idea of the summary. :+1: I was also thinking about an "info" command that tells you either some general information about the project or detailed information about a package (how much variants, active overrides, you name it...).

**Comment by rhubert** [comment]
The `info` command sounds interesting. Maybe in the future recipes have a optional 'info:' section where you can add some human readable info's about the package,... But I think you may need a lot of arguments for the info command. Otherwise you'll possibly get to much informations on large projects? 

Maybe the scmOverrides-info can also be added to the `status` command?

**Comment by rhubert** [comment]
I started working on this (see  #109)  and added some statistics as well as informations on overridden scm.

Example Output:
```
bob dev ...
Build result is in ....
checkoutSteps: 2
buildSteps:    2
packageSteps:  2
scms: 2
 -> overridden: 1
   -> packages: ['root']
```

```
bob status root
>> root
scm's Overridden by override:
match: {'url': 'file:///tmp/test/'}
matched to:
{'url': 'file:///tmp/test/', 'dir': 'test', 'scm': 'git', 'recipe': 'recipes/root.yaml#0'}
```

Now I'm thinking about adding a 'name' property to scmOverride to increase readability of `status` output.... :thinking:
